export const ALLL_PRODUCT_REQUEST='ALLL_PRODUCT_REQUEST';
export const ALLL_PRODUCT_SUCCESS='ALLL_PRODUCT_SUCCESS';
export const ALLL_PRODUCT_FAIL='ALLL_PRODUCT_FAIL';


export const PRODUCT_DETAIL_REQUEST='PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS='PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL='PRODUCT_DETAIL_FAIL';
export const CLEAR_ERRORS='CLEAR_ERRORS';